INSERT INTO categorias (descricao) VALUES
('Doces 🍬'),
('Salgados 🧀'),
('Massas 🍝'),
('Bebidas 🍹'),
('Saudável 💪'),
('Sobremesas 🍰'),
('Lanches 🥪'),
('Café da Manhã 🥞'),
('Jantares 🍽️'),
('Pratos Rápidos ⏱️'),
('Vegetariano 🥕'),
('Vegano 🌱'),
('Outros 📦'),
('Carnes 🥩'),
('Aves 🍗'),
('Peixes e Frutos do Mar 🐟'),
('Sopas e Caldos 🥣'),
('Acompanhamentos 🍚'),
('Molhos e Temperos 🌶️'),
('Culinária Internacional 🌍');
